#!/bin/bash

find . -type f -name ".*" -o -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f

#find . -type f -name '.*gif' -exec sh -c 'echo "${0%.gif}"' {} \; | sort -f | awk '!seen[$0]++'

